package com.netki.model

enum class Attestation(id: Int) {
    ADDRESS_1(0),
    ADDRESS_2(1),
    BENEFICIARY_PERSON_FIRST_NAME(2),
    BENEFICIARY_PERSON_LAST_NAME(3),
    BIRTH_DATE(4),
    BIRTH_PLACE(5),
    COUNTRY_OF_RESIDENCE(6),
    CUSTOMER_IDENTIFICATION(7),
    ISSUING_COUNTRY(8),
    LEGAL_PERSON_NAME(9),
    NATIONAL_IDENTIFIER(10),
    NATIONAL_IDENTIFIER_NUMBER(11),
    NATURAL_PERSON_FIRST_NAME(12),
    NATURAL_PERSON_LAST_NAME(13),
    ACCOUNT_NUMBER(14),
    REGISTRATION_AUTHORITY(15)
}
